SATProject/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SATProject;
using PagedList;

namespace SATProject.Controllers
{ 
    public class EnrollmentController : Controller
    {
        private SATEntities db = new SATEntities();

        //
        // GET: /Enrollment/

        public ViewResult Index(string search = "", string courseName = "", int page = 1)
        {
            var enrollments = db.Enrollments.Include("ScheduledClass").Include("Student").ToList();
            //if the search string has a value apply the search
            if (search != "")
            {
                search = search.ToLower();

                enrollments = (from c in enrollments
                           where c.ScheduledClass.Cours.courseName.ToLower().Contains(search) ||
                           c.Student.firstName.ToLower().Contains(search) ||
                           c.Student.lastName.ToLower().Contains(search)
                           select c).ToList();
            }//end if
            if (courseName != "")
            {
                enrollments = (from c in enrollments
                           where c.ScheduledClass.Cours.courseName == courseName
                           select c).ToList();
            }//end if
            //dropdownlist for CourseName

            //distinct list of Course names
            var courses = (from c in db.Enrollments
                         select c.ScheduledClass.Cours.courseName).Distinct().ToList();
            //add A SELECT LIST to the ViewBag for the DropDown
            ViewBag.CourseName = new SelectList(courses);

            //search params must be added to the viewbag in order to
            //keep them as we page
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentCourse = courseName;

            int pageSize = 5;
            //make sure page doesn't drop below 1
            page = page <= 0 ? 1 : page;

            return View(enrollments.ToPagedList(page, pageSize));
        }

        //
        // GET: /Enrollment/Details/5

        public ViewResult Details(int id)
        {
            Enrollment enrollment = db.Enrollments.Single(e => e.enrollmentId == id);
            return View(enrollment);
        }

        //
        // GET: /Enrollment/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.scheduledClassId = new SelectList(GetClassDdlItems(), "ID", "Name");

            //student ddl

            ViewBag.studentId = new SelectList(GetStudentDdlItems(), "ID", "Name");
            return View();
        }

        private List<DropDownItem> GetStudentDdlItems()
        {
            var students = (from s in db.Students.ToList()
                            orderby s.lastName
                            where s.statusId == 1
                            select new DropDownItem()
                            {
                                ID = s.studentId,
                                Name = string.Format(
                                "{0}, {1} - ID:{2}",
                                s.lastName, s.firstName, s.studentId)
                            }).ToList();
            return students;
        }

        private List<DropDownItem> GetClassDdlItems()
        {
            var classes = (from c in db.ScheduledClasses.ToList()
                           orderby c.startDate descending
                           where c.statusId != 3
                           select new DropDownItem()
                           {
                               ID = c.scheduledClassId,
                               //Name is what will show in the DDL
                               Name = string.Format(
                               "{0} - {1:d}", c.Cours.courseName, c.startDate)
                           }).ToList();
            return classes;
        } 

        //
        // POST: /Enrollment/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.AddObject(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.scheduledClassId = new SelectList(GetClassDdlItems(), "ID", "Name", enrollment.scheduledClassId);
            ViewBag.studentId = new SelectList(GetStudentDdlItems(), "ID", "Name", enrollment.studentId);
            return View(enrollment);
        }
        
        //
        // GET: /Enrollment/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Enrollment enrollment = db.Enrollments.Single(e => e.enrollmentId == id);
            ViewBag.scheduledClassId = new SelectList(GetClassDdlItems(), "ID", "Name", enrollment.scheduledClassId);
            ViewBag.studentId = new SelectList(GetStudentDdlItems(), "ID", "Name", enrollment.studentId);
            return View(enrollment);
        }

        //
        // POST: /Enrollment/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Attach(enrollment);
                db.ObjectStateManager.ChangeObjectState(enrollment, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.scheduledClassId = new SelectList(GetClassDdlItems(), "ID", "Name", enrollment.scheduledClassId);
            ViewBag.studentId = new SelectList(GetStudentDdlItems(), "ID", "Name", enrollment.studentId);
            return View(enrollment);
        }

        //
        // GET: /Enrollment/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Enrollment enrollment = db.Enrollments.Single(e => e.enrollmentId == id);
            return View(enrollment);
        }

        //
        // POST: /Enrollment/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Enrollment enrollment = db.Enrollments.Single(e => e.enrollmentId == id);
            db.Enrollments.DeleteObject(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }//end controller
    public class DropDownItem
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}//end namespace

SATProject/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SATProject;
using PagedList;

namespace SATProject.Controllers
{ 
    public class ScheduleController : Controller
    {
        private SATEntities db = new SATEntities();

        //
        // GET: /Schedule/

        public ViewResult Index(string search = "", string instructorName = "", bool showInactive = false,
            int page = 1)
        {
            var scheduledclasses = db.ScheduledClasses.Include("Cours").Include("ScheduledClassStatu").ToList();

            if (search != "")
            {
                search = search.ToLower();

                scheduledclasses = (from c in scheduledclasses
                           where c.Cours.courseName.ToLower().Contains(search) ||
                           c.instructorName.ToLower().Contains(search)
                           select c).ToList();
            }//end if
            if (instructorName != "")
            {
                scheduledclasses = (from c in scheduledclasses
                                    where c.instructorName == instructorName
                                    select c).ToList();
            }//end if
            if (showInactive)
            {
                scheduledclasses = (from c in scheduledclasses
                           where c.statusId == 3 ||
                           c.statusId == 2
                           select c).ToList();
            }
            else
            {
                scheduledclasses = (from c in scheduledclasses
                           where c.statusId == 1
                           select c).ToList();
            }
            //non admins should only see active courses
            if (!User.IsInRole("Admin"))
            {
                scheduledclasses = (from c in scheduledclasses
                           where c.statusId == 1
                           select c).ToList();
            }//end if

            //dropdownlist for department

            //distinct list of department names
            var instructors = (from c in db.ScheduledClasses
                                  select c.instructorName).Distinct().ToList();
            //add A SELECT LIST to the ViewBag for the DropDown
            ViewBag.instructorName = new SelectList(instructors);

            //search params must be added to the viewbag in order to
            //keep them as we page
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentDept = instructorName;

            int pageSize = 5;
            //make sure page doesn't drop below 1
            page = page <= 0 ? 1 : page;

            return View(scheduledclasses.ToPagedList(page, pageSize));
        }

        //
        // GET: /Schedule/Details/5

        public ViewResult Details(int id)
        {
            ScheduledClass scheduledclass = db.ScheduledClasses.Single(s => s.scheduledClassId == id);
            return View(scheduledclass);
        }

        //
        // GET: /Schedule/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.courseId = new SelectList(db.Courses, "courseId", "courseName");
            ViewBag.statusId = new SelectList(db.ScheduledClassStatus, "SCSID", "SCSName");
            return View();
        } 

        //
        // POST: /Schedule/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(ScheduledClass scheduledclass)
        {
            if (ModelState.IsValid)
            {
                db.ScheduledClasses.AddObject(scheduledclass);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.courseId = new SelectList(db.Courses, "courseId", "courseName", scheduledclass.courseId);
            ViewBag.statusId = new SelectList(db.ScheduledClassStatus, "SCSID", "SCSName", scheduledclass.statusId);
            return View(scheduledclass);
        }
        
        //
        // GET: /Schedule/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            ScheduledClass scheduledclass = db.ScheduledClasses.Single(s => s.scheduledClassId == id);
            ViewBag.courseId = new SelectList(db.Courses, "courseId", "courseName", scheduledclass.courseId);
            ViewBag.statusId = new SelectList(db.ScheduledClassStatus, "SCSID", "SCSName", scheduledclass.statusId);
            return View(scheduledclass);
        }

        //
        // POST: /Schedule/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(ScheduledClass scheduledclass)
        {
            if (ModelState.IsValid)
            {
                db.ScheduledClasses.Attach(scheduledclass);
                db.ObjectStateManager.ChangeObjectState(scheduledclass, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.courseId = new SelectList(db.Courses, "courseId", "courseName", scheduledclass.courseId);
            ViewBag.statusId = new SelectList(db.ScheduledClassStatus, "SCSID", "SCSName", scheduledclass.statusId);
            return View(scheduledclass);
        }

        //
        // GET: /Schedule/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            ScheduledClass scheduledclass = db.ScheduledClasses.Single(s => s.scheduledClassId == id);
            return View(scheduledclass);
        }

        //
        // POST: /Schedule/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            ScheduledClass scheduledclass = db.ScheduledClasses.Single(s => s.scheduledClassId == id);
            db.ScheduledClasses.DeleteObject(scheduledclass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SATProject/Views/Schedule/Create.cshtml
@model SATProject.ScheduledClass

@{
    ViewBag.Title = "Create Schedule";
}

<h2>Create Schedule</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <div id="courseWrapper">
        <div id="courseHeader">
            <h1>Schedule</h1><br />
        </div>
        <div id="courseRight">
            @Html.LabelFor(model => model.courseId, "Course"):
            @Html.DropDownList("courseId", String.Empty)
            @Html.ValidationMessageFor(model => model.courseId)<br /><br />
            @Html.LabelFor(model => model.startDate):
            @Html.EditorFor(Model => Model.startDate)<br /><br />
            @Html.ValidationMessageFor(model => model.startDate)
            @Html.LabelFor(model => model.endDate):
            @Html.EditorFor(Model => Model.endDate)<br /><br />
            @Html.ValidationMessageFor(model => model.endDate)
            @Html.LabelFor(model => model.creditHours):
            @Html.EditorFor(model => model.creditHours)
            @Html.ValidationMessageFor(model => model.creditHours)<br /><br />
            @Html.LabelFor(model => model.instructorName):
            @Html.EditorFor(model => model.instructorName)
            @Html.ValidationMessageFor(model => model.instructorName)<br /><br />
            @Html.LabelFor(model => model.location):
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)<br /><br />
            @Html.LabelFor(model => model.statusId, "Class Status"):
            @Html.DropDownList("statusId", String.Empty)
            @Html.ValidationMessageFor(model => model.statusId)
        </div>
        <div id="courseFooter">
            <br />
            <input type="submit" value="Create Schedule" />
            <br /><br />
            @Html.ActionLink("Back to Schedules", "Index")
        </div>
    </div>
    
            

            
}

    

SATProject/Views/Schedule/Delete.cshtml
@model SATProject.ScheduledClass

@{
    ViewBag.Title = "Delete Schedule";
}

<h2>Delete Schedule</h2>

<h3>Are you sure you want to delete this?</h3>
<div id="courseWrapper">
    <div id="courseHeader">
        <h1>Schedule</h1><br />
    </div>
    <div id="courseRight">
        Course:
        @Html.DisplayFor(model => model.Cours.courseName)<br /><br />
        Start Date:
        @Html.DisplayFor(model => model.startDate)<br /><br />
        End Date:
        @Html.DisplayFor(model => model.endDate)<br /><br />
        Credit Hours:
        @Html.DisplayFor(model => model.creditHours)<br /><br />
        Instructor Name:
        @Html.DisplayFor(model => model.instructorName)<br /><br />
        Location:
        @Html.DisplayFor(model => model.location)<br /><br />
        Class Status:
        @Html.DisplayFor(model => model.ScheduledClassStatu.SCSName)
    </div>

    <div id="courseFooter">
        @using (Html.BeginForm()) {        
        <br />
        <input type="submit" value="Delete Schedule" />
            <br /><br />
        @Html.ActionLink("Back to Schedules", "Index")
        }
    </div>
</div>

        

SATProject/Views/Schedule/Details.cshtml
@model SATProject.ScheduledClass

@{
    ViewBag.Title = "Schedule Details";
}

<h2>Schedule Details</h2>

<div id="courseWrapper">
    <div id="courseHeader">
        <h1>Schedule</h1><br />
    </div>
    <div id="courseRight">
        Course:
        @Html.DisplayFor(model => model.Cours.courseName)<br /><br />
        Start Date:
        @if (Model.startDate == null)
            {
                @:&nbsp;No Start Date Assigned.
            }
            else
            {
        @Html.DisplayFor(model => model.startDate)
        }
        <br /><br />
        End Date:
        @if (Model.endDate == null)
            {
                @:&nbsp;No End Date Assigned.
            }
            else
            {
        @Html.DisplayFor(model => model.endDate)
        }
        <br /><br />
        Credit Hours:
        @if (Model.creditHours == null)
            {
                @:&nbsp;No Credit Hours Assigned.
            }
            else
            {
        @Html.DisplayFor(model => model.creditHours)
        }
        <br /><br />
        Instructor Name:
        @if (Model.instructorName == null)
            {
                @:&nbsp;No Instructor Assigned.
            }
            else
            {
        @Html.DisplayFor(model => model.instructorName)
        }
        <br /><br />
        Location:
        @if (Model.location == null)
            {
                @:&nbsp;No Location Assigned.
            }
            else
            {
        @Html.DisplayFor(model => model.location)
        }
        <br /><br />
        Status:
        @Html.DisplayFor(model => model.ScheduledClassStatu.SCSName)
    </div>
    <div id="courseFooter">
        @if (User.IsInRole("Admin"))
        {
        <br />
        @Html.ActionLink("Edit Schedule", "Edit", new { id=Model.scheduledClassId })        
        <br /><br />
            }
        @Html.ActionLink("Back to Schedules", "Index")
        <br /><br />
        @Html.ActionLink("View Enrollments", "Index", "Enrollment")
    </div>
</div>
        


    

SATProject/Views/Schedule/Edit.cshtml
@model SATProject.ScheduledClass

@{
    ViewBag.Title = "Edit Course Schedule";
}

<h2>Edit Course Schedule</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.scheduledClassId)

    <div id="courseWrapper">
        <div id="courseHeader">
            <h1>Schedule</h1><br />
        </div>
        <div id="courseRight">
            @Html.LabelFor(model => model.courseId, "Course"):
            @Html.DropDownList("courseId", String.Empty)
            @Html.ValidationMessageFor(model => model.courseId)<br /><br />
            @Html.LabelFor(model => model.startDate):
            @Html.EditorFor(Model => Model.startDate)
            @Html.ValidationMessageFor(model => model.startDate)<br /><br />
            @Html.LabelFor(model => model.endDate):
            @Html.EditorFor(Model => Model.endDate)
            @Html.ValidationMessageFor(model => model.endDate)<br /><br />
            @Html.LabelFor(model => model.creditHours):
            @Html.EditorFor(model => model.creditHours)
            @Html.ValidationMessageFor(model => model.creditHours)<br /><br />
            @Html.LabelFor(model => model.instructorName):
            @Html.EditorFor(model => model.instructorName)
            @Html.ValidationMessageFor(model => model.instructorName)<br /><br />
            @Html.LabelFor(model => model.location):
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location)<br /><br />
            @Html.LabelFor(model => model.statusId, "Class Status"):
            @Html.DropDownList("statusId", String.Empty)
            @Html.ValidationMessageFor(model => model.statusId)
        </div>
        <div id="courseFooter">
            <br />
            <input type="submit" value="Save Changes" />
            <br /><br />
            @Html.ActionLink("Back to Schedules", "Index")
        </div>
    </div>
}

    

SATProject/Views/Schedule/Index.cshtml
@model PagedList.IPagedList<SATProject.ScheduledClass>

@{
    ViewBag.Title = "Class Schedules";
}

<h2>Class Schedules</h2>
@if (User.IsInRole("Admin"))
{
    <br />
<p class="createNew">
    @Html.ActionLink("Create New Class Schedule", "Create")
</p>
}
<script>

    $(function () {
        //click even for the reset button
        $("#reset").click(function () {
            //clear the textbox
            $("#search").val("");
            $("#instructorName").val("");
            //resubmit the form
            document.forms[0].submit();
        });
    });
</script>
@using (Html.BeginForm())
{
    <fieldset>
        <legend>Search Class Schedule</legend>
        <div><span class="inActive">Search:</span>@Html.TextBox("search")
            @Html.DropDownList("instructorName", "[ Filter by Instructor ]")
            @*the name of the dropdownlist MUST match the name of the SelectList in the ViewBag*@
            <input type="submit" value="Go!" />
            <input type="button" id="reset" value="Reset" />
            @if (User.IsInRole("Admin"))
            {
            <span class="inActive">Inactive Classes:</span>
            @Html.CheckBox("showInactive",
            new { onchange = "document.forms[0].submit();" })
            }
        </div>
    </fieldset>
    <br /><br />
}
@using (Html.BeginForm())
{
        <div class="paging">

        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        of @Model.PageCount

        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("<<", "Index", new { page = 1, pageSize = ViewBag.pageSize, search = ViewBag.CurrentSearch, instructorName = ViewBag.CurrentDept })
            @:&nbsp;
            @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, pageSize = ViewBag.pageSize, search = ViewBag.CurrentSearch, instructorName = ViewBag.CurrentDept })
        }
        else
        {
            @Html.Raw("&lt;&lt;&nbsp;&lt; Prev")
        }

        @if (Model.HasNextPage)
        {
            @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, pageSize = ViewBag.pageSize, search = ViewBag.CurrentSearch, instructorName = ViewBag.CurrentDept })
            @:&nbsp;
            @Html.ActionLink(">>", "Index", new { page = Model.PageCount, pageSize = ViewBag.pageSize, search = ViewBag.CurrentSearch, instructorName = ViewBag.CurrentDept })
        }
        else
        {
            @Html.Raw("Next &gt;&nbsp;&gt;&gt;")
        }
       
    </div>
}
@foreach (var item in Model) {
            
    <div id="indexWrapper">
        <div id="indexHeader">
            Course:<br /><br />
            Start Date:<br /><br />
            End Date:<br /><br />
            Instructor:<br /><br />
            Status:
        </div>
        <div id="indexBody">
            @Html.ActionLink(item.Cours.courseName, "Details", "Course", new { id=item.courseId }, null)<br /><br />
            @Html.DisplayFor(modelItem => item.startDate)<br /><br />
            @Html.DisplayFor(modelItem => item.endDate)<br /><br />
            @Html.DisplayFor(modelItem => item.instructorName)<br /><br />
            @Html.DisplayFor(modelItem => item.ScheduledClassStatu.SCSName)
        </div>
        <div id="indexFooterS">
            @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Edit", "Edit", new { id=item.scheduledClassId })
            <br /><br />      
            @Html.ActionLink("Delete", "Delete", new { id=item.scheduledClassId })
        }
            <br /><br />
            @Html.ActionLink("Details", "Details", new { id=item.scheduledClassId }) 
        </div>
    </div>
}